function cockandballs() {
    var messages = [
      `i dont think am ok`,
      `dude can you like shut the fuck up`,
      `h`,
      `technoblade never dies`,
      `stay in school kids it makes you better at pvp`,
      `corn :fire:`,
      `ohio??`,
      `bench communist republic`,
      `bench communist republic`,
      `am not a commie i think`,
      `also try terraria and minecraft`,
      `texting people is my hobby, harrassing them is my passion`,
      `also try cbt`,
      `also try cbt x2`,
      `also try cRt`,
      `who starts a conversation like that? i just sat down!`,
      `did you know the only joke my mother made was 14 years ago`,
      `alive, alert and causing concern`,
      `dead, aloof, and still causing concern`,
      `the only soul i need is the one to find me the will to live`,
      `made in china`,
      `what if i put you in a jar`,
        `truly a quote of all time`,
        `cannibalism is a viable way of reducing the overpopulation problem`,
        `does the alpha make the omega or the omega make the alpha`,
        `gingerbrave aint running faster than the homing missile i sent`,
        `the power lies in the people until they drop dead`,
        `polen kannot into spaec`,
        `crazy? i was crazy once`,
        `one must imagine a coder happy`,
        `i just want to talk to him`,
        `obliteration of the self`,
        `asterLP`,
        `asterOS`,
        `go4schools.github.io/projectbyp/`,
        `doing gods work without pay`,
        `benchic asfaleiocracy is nice`,
        `deer lourdes`,
        `sleep is a type of meditation im not gonna use`,
        `if she leaves you for another there is always her brother`,
        `bond with the lizard`,
        `i just gave you prostate cancer`,
        `sorry about the syphilis`,
        `you cant put loyalty on a hoe`,
        `stop it, get some help`,
        `literally 1984`,
        `eugh an eraser`,
        `swallowing a big girthy banana rn`,
        `<span class="ikibimi">ancient ikibimi</span>`,
        `2 + 2 is fish<br/>change my mind`,
        `imagine<br>inagime breathing oxygen`,
        `cheese`,
        `hi kommit`,
        `you people arent very nice`,
        `<span style="color:green;">WHY EM SEE Æ</span>`,
        `waxed lightly weathered cut copper stairs`,
        `menace to society since 2011`,
        `made from stars`,
        `you cant escape from the heat death of the universe`,
        `remember its cognitive behavioral therapy!`,
        `the tism is tickling my brain`,
        `somehow good at everything that wont earn me money :pensive:`,
        `the only inevitable thing other than the heat death of the universe is taxes`,
        `<span style="color:#6495ed;font-family:Tahoma, Verdana, sans-serif;">its the IRS oh no</span>`,
        `in the name of the Oven, the Dough and the Witches`,
        `thus began the Dark Flour War`,
        `in this dream things arent as they seem`,
        `funkinosc v69 when`,
        `staring into the abyss until it stares back`,
        `we are runners we are makers we're making good`,
        `life isnt fair`,
        `sybau`,
        `gimme 30 seconds`,
        `fully automated luxury gay space communism`,
        `print("your mother")`,
        `refusing to draw humans since 2023`,
        `:notes: can i get my ballz in yo jawz,,,:notes:`,
        `my name jeff`,
        `god dammit son`,
        `my dad told me not to commit tax fraud :D`,
        `whats 9 + 10`,
        `specimen a in action`,
        `stop sexually harassing the table`,
        `melony: nooo ur supposed to expose someone else!! <br/> the seven expose doc tabs:`,
        `not even god is ready for my arrival`,
        `beantoast nation make way for fjordland`,
        `im meerhagening it so good`,
        `indeks.html`,
        `men, go eat his ass`,
        `zamn :drool:`,
        `<span style="color:#ffcd9c;">i havent <i>killed</i> all those children 4 years ago</span>`,
        `<span style="color:#00bbff;">listen kid. aster, they're hiding something. i need to tell you before i get sho-<br/> -a dead kommit</span>`,
        `<span style="color:#00ff00;">i have thirty babies<br/> -echo, still high on weed</span>`,
        `<span style="color:#ffcd9c;">when the dust settles, just you and me remain.</span>`,
        `<span style="color:#ffcd9c;">https://files.catbox.moe/jbfwh6.jpg</span>`,
        `also try https://kommittt.github.io/ !`,
        `dont eat ass, in the halls<br>don't eat ass, in the halls`,
        `chaos, chaos!`,
        `i can't do anything`,
        `portal to cool sites and shitholes`,
        `THE NETHER :fire:`,
        `running on about as much code as a fly's brain can handle in a second`,
        `organizing code? whats that?`,
        `int main() { std::cout << "Hello world"; return 0;}`,
        `C++ beginner since 2025`,
        `no one seems to care that i exist and even i dont when im pissed /lyr`,
        `holyfuck.js`,
        `return to nothing`,
        `fuck you too kommit <3`,
        `IM NOT A FEMBOY AHHHHHHH`,
        `eating ass, in teh halls<br>eating ass, in teh halls`,
        `Dying of Death in this Forsakened place`,
        `florence give up your pointless struggle against the gay`,
        `now with gender crisis`,
        `kommit stop stealing my shit`,
        `at least he knows how to string together code`,
        `plundering for functional css and javascript`,
        `about as optimized as my brain is for new information`,
        `held together by hopes, dreams, a bit of duct tape and a <i><b>blessing from the digital gods</b></i>`,
        `wait, you're supposed to write your own code?`,
        `freedom must reign over every last star`,
        `helldivers never die`,
        `earth is cool <br/> some might even call it super`,
        `yeah i can read code but i sure as fuck cant write it`,
        `seka dzxarcxo, duo kecxe se?`,
        `o paixao, xi nasxekam,`,
        `soli ximam, ledon luro,`,
        `seka amxai ximam sako!`,
        `Steel yourselves helldivers, we're going in`,
        `Get out there and dispense justice with extreme prejudice!`,
        `fuck you, fuck you and fuck you specifically!`,
        `alive since 11th december 2025`,
        `i eated it`,
        `echo my man keep your foot fetish out of my line of sight`,
        `mmm cornballs`,
        `the great meme reset is fake`,
        `look at the stars. what do you see?`,
        `mfw half the pages on here arent even a quarter of the way done`,
        `oh boy new website`,
        `also try the older site at root!`,
        `neverending alpha since 2026`,
        `covid was 6 yearsd ago??`,
        `caked up regiment`,
        `in this world, its milk or BE MILKED!`,
        `troodles is real`,
        `some of these splash texts have been here since like 2024 i kid you not`,
        `moving from stealing code from websites to learning code from stackoverflow`,
    ];

    var rText = Math.floor(Math.random() * messages.length);
    
    document.getElementById("randomsplash").innerHTML = messages[rText];

    const clickSplash = document.getElementById("randomsplash");

    clickSplash.addEventListener("click", () => {
        var rText = Math.floor(Math.random() * messages.length);
        document.getElementById("randomsplash").innerHTML = messages[rText];
    });
}
cockandballs();